"""Migrate food inventory from local SQLite to Supabase."""

import sqlite3
from pathlib import Path

try:
    from supabase import create_client
except ImportError:
    print("Install the supabase package first:")
    print("  pip install supabase")
    raise SystemExit(1)

# --- Configuration ---
SUPABASE_URL = "https://qkvkivmzlxjanjlymhsi.supabase.co"
SUPABASE_KEY = (
    "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9."
    "eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFrdmtpdm16bHhqYW5qbHltaHNpIiwi"
    "cm9sZSI6ImFub24iLCJpYXQiOjE3NzE3OTA2OTIsImV4cCI6MjA4NzM2NjY5Mn0."
    "hIWlrznnqvP5ClxZENXM4793o-6casfLa2R8Qf8isU4"
)

DB_PATH = Path(__file__).parent / "food_inventory.db"


def migrate(clear_first=False):
    # 1. Read items from SQLite
    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row
    rows = conn.execute(
        "SELECT name, quantity, unit, category FROM inventory ORDER BY id"
    ).fetchall()
    conn.close()

    items = [dict(r) for r in rows]
    print(f"Read {len(items)} items from SQLite.")

    # 2. Connect to Supabase
    supabase = create_client(SUPABASE_URL, SUPABASE_KEY)

    # 3. Optionally clear existing data
    if clear_first:
        print("Clearing existing inventory...")
        supabase.table("inventory").delete().neq("id", 0).execute()
        print("  Cleared.")

    # 4. Insert items in batches
    BATCH_SIZE = 50
    for i in range(0, len(items), BATCH_SIZE):
        batch = items[i : i + BATCH_SIZE]
        supabase.table("inventory").insert(batch).execute()
        print(f"  Inserted batch {i // BATCH_SIZE + 1}: {len(batch)} items")

    print(f"\nDone! Migrated {len(items)} items to Supabase.")


if __name__ == "__main__":
    print("=== Supabase Migration ===\n")
    print("STEP 1: Go to Supabase Dashboard > SQL Editor and run this SQL:\n")
    print("""CREATE TABLE inventory (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  quantity REAL NOT NULL,
  unit TEXT NOT NULL,
  category TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Allow public read/write access
ALTER TABLE inventory ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow all access" ON inventory
  FOR ALL USING (true) WITH CHECK (true);
""")
    answer = input("Have you created the table? (y/n): ").strip().lower()
    if answer == "y":
        clear = input("Clear existing data first? (y/n): ").strip().lower() == "y"
        migrate(clear_first=clear)
    else:
        print("Create the table first, then run this script again.")
